In [54]:
import pandas as pd
import numpy as np
from collections import defaultdict
from math import cos,sin,pi

In [55]:
df = pd.read_csv("./recordings/round_0.csv")

In [56]:
df.index.name = "index"
df.tail()

frame_id   id                       type_id       pos_x       pos_y  \
index                                                                         
159688      1499  319  vehicle.dodge_charger.police  -24.619755    6.242687   
159689      1499  320       vehicle.bmw.grandtourer -145.456726   -7.497466   
159690      1499  321            vehicle.audi.etron  203.695114  179.711136   
159691      1499  322            vehicle.audi.etron   32.851929   -4.568919   
159692      1499  324       vehicle.mustang.mustang  170.317673   68.340813   

           pos_z      roll     pitch         yaw  velocity_x  ...  \
index                                                         ...   
159688 -0.023939 -0.006073  0.247779   42.445663    2.991448  ...   
159689  0.073846  0.002574  0.017274  -89.882317    0.007906  ...   
159690  2.258767 -0.540100  1.344256  147.683029   -7.360792  ...   
159691 -0.036358 -0.004120  0.010607 -179.060989   -4.567746  ...   
159692  0.071143  0.469124 -0.278685  -96.875031   -0.936704  ...   

        angular_vel_x  angular_vel_y  angular_vel_z  bbox3d_offset_x  \
index                                                                  
159688      -0.013089      -0.013067      16.708675         0.013744   
159689       0.005086       0.000101      -0.062803         0.000000   
159690      -0.012444      -0.445449       6.890909        -0.005178   
159691       0.000927       0.000022       0.111359        -0.005178   
159692       0.136552       0.434835     -11.885408         0.060645   

        bbox3d_offset_y  bbox3d_offset_z  bbox3d_extent_x  bbox3d_extent_y  \
index                                                                        
159688         0.000000         0.788012         2.505488         1.027168   
159689         0.000000         0.760000         2.319544         1.129661   
159690         0.023936         0.813284         2.446003         1.043161   
159691         0.023936         0.813284         2.446003         1.043161   
159692         0.000000         0.747342         2.452351         1.030329   

        bbox3d_extent_z  traffic_light_color  
index                                         
159688         0.790352                  NaN  
159689         0.839089                  NaN  
159690         0.825575                  NaN  
159691         0.825575                  NaN  
159692         0.739199                  NaN  

[5 rows x 25 columns]

In [57]:
vehicles = df.query('type_id.str.contains("vehicle")')
agent_wise_idxs = vehicles.groupby('id').groups

In [58]:
vehicles

frame_id   id                       type_id       pos_x       pos_y  \
index                                                                         
63             0  255       vehicle.lincoln.mkz2017  245.865112   -9.996704   
65             0  256       vehicle.bmw.grandtourer   -9.205211  179.851013   
67             0  257            vehicle.citroen.c3  -77.887169   99.723961   
69             0  258         vehicle.volkswagen.t2  199.419632   -5.502129   
71             0  259         vehicle.volkswagen.t2   81.363419 -124.476494   
...          ...  ...                           ...         ...         ...   
159688      1499  319  vehicle.dodge_charger.police  -24.619755    6.242687   
159689      1499  320       vehicle.bmw.grandtourer -145.456726   -7.497466   
159690      1499  321            vehicle.audi.etron  203.695114  179.711136   
159691      1499  322            vehicle.audi.etron   32.851929   -4.568919   
159692      1499  324       vehicle.mustang.mustang  170.317673   68.340813   

           pos_z      roll     pitch         yaw    velocity_x  ...  \
index                                                           ...   
63      0.086179  0.000000  0.000000  -88.606743 -1.391450e-07  ...   
65      0.111811  0.000000  0.000000   89.637466 -1.224868e-06  ...   
67      0.494158 -0.000732 -0.123565  -90.156242 -1.802880e-04  ...   
69      0.063131  0.000000  0.000000 -179.144165  0.000000e+00  ...   
71      8.093420  0.000000  0.000000   92.024109  0.000000e+00  ...   
...          ...       ...       ...         ...           ...  ...   
159688 -0.023939 -0.006073  0.247779   42.445663  2.991448e+00  ...   
159689  0.073846  0.002574  0.017274  -89.882317  7.906466e-03  ...   
159690  2.258767 -0.540100  1.344256  147.683029 -7.360792e+00  ...   
159691 -0.036358 -0.004120  0.010607 -179.060989 -4.567746e+00  ...   
159692  0.071143  0.469124 -0.278685  -96.875031 -9.367037e-01  ...   

        angular_vel_x  angular_vel_y  angular_vel_z  bbox3d_offset_x  \
index                                                                  
63       1.824800e-05       0.000002   2.577838e-08         0.060645   
65       2.445680e-07      -0.000092   4.681375e-09         0.000000   
67      -1.122831e+01      -0.004284  -1.878043e-04         0.000000   
69       0.000000e+00       0.000000   0.000000e+00         0.000000   
71       0.000000e+00       0.000000   0.000000e+00         0.000000   
...               ...            ...            ...              ...   
159688  -1.308868e-02      -0.013067   1.670868e+01         0.013744   
159689   5.086339e-03       0.000101  -6.280322e-02         0.000000   
159690  -1.244391e-02      -0.445449   6.890909e+00        -0.005178   
159691   9.267320e-04       0.000022   1.113589e-01        -0.005178   
159692   1.365520e-01       0.434835  -1.188541e+01         0.060645   

        bbox3d_offset_y  bbox3d_offset_z  bbox3d_extent_x  bbox3d_extent_y  \
index                                                                        
63             0.000000         0.747342         2.452351         1.030329   
65             0.000000         0.760000         2.319544         1.129661   
67             0.000000         0.770000         1.987674         0.931037   
69             0.000000         1.025817         2.236856         0.905625   
71             0.000000         1.025817         2.236856         0.905625   
...                 ...              ...              ...              ...   
159688         0.000000         0.788012         2.505488         1.027168   
159689         0.000000         0.760000         2.319544         1.129661   
159690         0.023936         0.813284         2.446003         1.043161   
159691         0.023936         0.813284         2.446003         1.043161   
159692         0.000000         0.747342         2.452351         1.030329   

        bbox3d_extent_z  traffic_light_color  
index                                         
63        

In [59]:
df.iloc[agent_wise_idxs[295]]

frame_id   id                      type_id       pos_x       pos_y  \
index                                                                        
124            0  295  vehicle.mercedes-benz.coupe -100.469582   16.268553   
232            1  295  vehicle.mercedes-benz.coupe -100.469772   16.268763   
340            2  295  vehicle.mercedes-benz.coupe -100.469704   16.268702   
448            3  295  vehicle.mercedes-benz.coupe -100.469582   16.268597   
556            4  295  vehicle.mercedes-benz.coupe -100.469467   16.268505   
...          ...  ...                          ...         ...         ...   
126691      1177  295  vehicle.mercedes-benz.coupe -103.921547 -137.082367   
126796      1178  295  vehicle.mercedes-benz.coupe -103.921547 -137.082367   
126901      1179  295  vehicle.mercedes-benz.coupe -103.921547 -137.082367   
127006      1180  295  vehicle.mercedes-benz.coupe -103.921547 -137.082367   
127111      1181  295  vehicle.mercedes-benz.coupe -103.921547 -137.082367   

           pos_z      roll     pitch         yaw  velocity_x  ...  \
index                                                         ...   
124     0.165673 -0.007233  0.466311  134.676819    0.001387  ...   
232     0.142713 -0.009033  0.527687  134.676819    0.000108  ...   
340     0.133514 -0.009216  0.508917  134.676773   -0.000211  ...   
448     0.130067 -0.009003  0.477150  134.676712   -0.000226  ...   
556     0.128932 -0.008759  0.450588  134.676666   -0.000172  ...   
...          ...       ...       ...         ...         ...  ...   
126691  0.407333  0.051119 -0.696959   -4.211732    0.000023  ...   
126796  0.407333  0.051119 -0.696959   -4.211732    0.000023  ...   
126901  0.407333  0.051119 -0.696959   -4.211732    0.000023  ...   
127006  0.407333  0.051119 -0.696959   -4.211732    0.000023  ...   
127111  0.407333  0.051119 -0.696959   -4.211732    0.000023  ...   

        angular_vel_x  angular_vel_y  angular_vel_z  bbox3d_offset_x  \
index                                                                  
124          1.214252   1.256142e+00       0.000393              0.0   
232          0.060262   7.046273e-02       0.000029              0.0   
340         -0.210646  -2.095246e-01      -0.000038              0.0   
448         -0.217276  -2.182679e-01      -0.000055              0.0   
556         -0.163604  -1.647793e-01      -0.000054              0.0   
...               ...            ...            ...              ...   
126691       0.000049  -2.463979e-05      -0.000264              0.0   
126796       0.000042  -1.854123e-05      -0.000264              0.0   
126901      -0.000012   9.676240e-06      -0.000263              0.0   
127006      -0.000031   9.500733e-07      -0.000263              0.0   
127111      -0.000003  -3.198900e-05      -0.000263              0.0   

        bbox3d_offset_y  bbox3d_offset_z  bbox3d_extent_x  bbox3d_extent_y  \
index                                                                        
124                 0.0             0.68         2.521893         1.081499   
232                 0.0             0.68         2.521893         1.081499   
340                 0.0             0.68         2.521893         1.081499   
448                 0.0             0.68         2.521893         1.081499   
556                 0.0             0.68         2.521893         1.081499   
...                 ...              ...              ...              ...   
126691              0.0             0.68         2.521893         1.081499   
126796              0.0             0.68         2.521893         1.081499   
126901              0.0             0.68         2.521893         1.081499   
127006              0.0             0.68         2.521893         1.081499   
127111              0.0             0.68         2.521893         1.081499   

        bbox3d_extent_z  traffic_light_color  
index                                         
124            0.820067                  NaN  
23

In [60]:
# for each vehicle, generate a R and T and a TF matrix per frame

# frame_wise_vehicle_tfs = {} # {frame_id:{veh_id:tf_mat}}
frame_wise_vehicle_tf = defaultdict(defaultdict)

In [63]:
# For each frame, for each vehicle, get the transform and generate the required feature map
# 2D R,T matrix 
def get_mat(x,y,t):
    rot = np.array([[cos(-t),-sin(-t),0],[sin(-t),cos(-t),0],[0,0,1]])
    trans = np.array([[1,0,-x],[0,1,-y],[0,0,1]])
    return rot@trans # first translate then rotate

In [64]:
for agent_id in agent_wise_idxs:
    agent_df = df.iloc[agent_wise_idxs[agent_id]]
    for idx,row in agent_df.iterrows():
        frame_id = row.frame_id
        frame_wise_vehicle_tf[frame_id][agent_id]={
            "mat": get_mat(row.pos_x,row.pos_y,row.yaw),
            "x":row.pos_x,"y":row.pos_y,"z":row.pos_z,"roll":row.roll,"pitch":row.pitch,"yaw":row.yaw
        }

    

In [110]:
# for frame_id in frame_wise_vehicle_tf:
#     for vehicle_id in frame_wise_vehicle_tf[frame_id]:
        
# For each vehicle, store a frame_wise map of all other vehicles(Transformed positions)
# as round_0_vehicle_0.csv
def transform_frame_df(frame_df,frame_id,center_agent_id,save_file=True,round_name="round_0"):
    mat = frame_wise_vehicle_tf[frame_id][agent_id]["mat"]
    frame_df_local = frame_df.copy()
    xy_hmg = frame_df_local[['pos_x','pos_y']].copy()
    xy_hmg['z'] = 1 # creating homogenous coordinate
    frame_df_local[['pos_x','pos_y']]=(mat@xy_hmg.T).T.values[:,:2]
    if save_file:
        frame_df_local.to_csv(f"agent_maps/{round_name}_vehicle_{center_agent_id}_frame_{frame_id}.csv")
    
#     (q@w@df_test.T).T.values[:,:2]
    
    
    

for agent_id in tqdm(agent_wise_idxs):
    agent_df = df.iloc[agent_wise_idxs[agent_id]]
    frame_ids = list(agent_df.frame_id)
    for frame_id in frame_ids:
        frame_df = df[df.frame_id==frame_id] # get full df for the given frame
        transform_frame_df(frame_df,frame_id,agent_id)

KeyboardInterrupt: 

In [99]:
df_test = df[['pos_x','pos_y']].head().copy()

In [100]:
df_test['z'] = 1

In [101]:
(q@w@df_test.T).T

0           1    2
index                             
0      -16.842549 -146.487900  1.0
1       60.527878 -213.168533  1.0
2      128.585617  -13.863537  1.0
3      187.834396    7.622720  1.0
4      187.860626   11.106436  1.0

In [102]:
df_test[['xnew','ynew']]=(q@w@df_test.T).T.values[:,:2]

In [103]:
df_test

pos_x       pos_y  z        xnew        ynew
index                                                   
0      148.487900  -14.842549  1  -16.842549 -146.487900
1      215.168533   62.527878  1   60.527878 -213.168533
2       15.863537  130.585617  1  128.585617  -13.863537
3       -5.622720  189.834396  1  187.834396    7.622720
4       -9.106436  189.860626  1  187.860626   11.106436

In [50]:
r = get_mat(5,5,pi/2)
r

array([[ 6.123234e-17,  1.000000e+00, -5.000000e+00],
       [-1.000000e+00,  6.123234e-17,  5.000000e+00],
       [ 0.000000e+00,  0.000000e+00,  1.000000e+00]])

In [51]:
r@np.array([[5,5,1]]).T

array([[0.],
       [0.],
       [1.]])

In [52]:
p1 = np.array([[5,5,1]]).T
p2 = np.array([[6,6,1]]).T

In [53]:
r@p1,r@p2

(array([[0.],
        [0.],
        [1.]]),
 array([[ 1.],
        [-1.],
        [ 1.]]))

In [41]:
t=pi/2
x,y = 2,2
q=np.array([[cos(-t),-sin(-t),0],[sin(-t),cos(-t),0],[0,0,1]])
w=np.array([[1,0,-x],[0,1,-y],[0,0,1]])

In [42]:
q

array([[ 6.123234e-17,  1.000000e+00,  0.000000e+00],
       [-1.000000e+00,  6.123234e-17,  0.000000e+00],
       [ 0.000000e+00,  0.000000e+00,  1.000000e+00]])

In [43]:
w

array([[ 1,  0, -2],
       [ 0,  1, -2],
       [ 0,  0,  1]])

In [46]:
q@w

array([[ 6.123234e-17,  1.000000e+00, -2.000000e+00],
       [-1.000000e+00,  6.123234e-17,  2.000000e+00],
       [ 0.000000e+00,  0.000000e+00,  1.000000e+00]])

In [47]:
q@w@p1

array([[ 3.],
       [-3.],
       [ 1.]])

In [48]:
q@w@p2

array([[ 4.],
       [-4.],
       [ 1.]])

In [107]:
grp = df.groupby(['frame_id','id'])

{(0, 1): [36], (0, 2): [37], (0, 3): [38], (0, 4): [39], (0, 5): [40], (0, 6): [41], (0, 7): [42], (0, 8): [43], (0, 9): [44], (0, 10): [45], (0, 11): [0], (0, 12): [1], (0, 13): [2], (0, 14): [3], (0, 15): [4], (0, 16): [5], (0, 17): [6], (0, 18): [7], (0, 19): [8], (0, 20): [9], (0, 21): [10], (0, 22): [11], (0, 23): [12], (0, 24): [13], (0, 25): [14], (0, 26): [15], (0, 27): [16], (0, 28): [17], (0, 29): [18], (0, 30): [19], (0, 31): [20], (0, 32): [21], (0, 33): [22], (0, 34): [23], (0, 35): [24], (0, 36): [25], (0, 37): [26], (0, 38): [27], (0, 39): [28], (0, 40): [29], (0, 41): [30], (0, 42): [46], (0, 43): [47], (0, 44): [48], (0, 45): [49], (0, 46): [50], (0, 47): [51], (0, 48): [52], (0, 49): [53], (0, 50): [54], (0, 51): [55], (0, 52): [56], (0, 53): [57], (0, 54): [58], (0, 55): [59], (0, 56): [60], (0, 57): [61], (0, 58): [62], (0, 59): [64], (0, 60): [66], (0, 61): [68], (0, 62): [70], (0, 63): [72], (0, 64): [74], (0, 65): [76], (0, 66): [78], (0, 67): [80], (0, 68): [82]

In [121]:
len(df.frame_id.unique()),len(df.id.unique())

(1500, 154)